---
- name: Get VMs
  hosts: esxi
  ignore_errors: true
  gather_facts: false
  roles:
    - dsu.ccdc.esxi
  vars:
    esxi_user: root
    # strategy: free

  tasks:
    - name: Import vars
      ansible.builtin.include_vars:
        dir: /home/ansible/vars/

    - name: Get all vm info
      delegate_to: localhost
      community.vmware.vmware_vm_info:
        hostname: "{{ inventory_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: false
      register: vm_info

    - name: Print VM info
      ansible.builtin.debug:
        var: vm_info

    - name: Export VM info to file
      delegate_to: localhost
      ansible.builtin.template:
        src: esxi.j2
        dest: /home/ansible/vars/{{ inventory_hostname }}.yml
        owner: ansible
        group: ansible
        mode: "0644"
