---
- name: ESXI vSwitch
  hosts: esxi
  ignore_errors: true
  gather_facts: false
  roles:
    - dsu.ccdc.esxi
  vars:
    esxi_user: root
  # strategy: free
    new_net: "lan"
  tasks:
    - name: Create vSwitch
      ansible.builtin.import_role:
        name: dsu.ccdc.esxi
        tasks_from: vswitch

    - name: Wait for confirmation
      ansible.builtin.pause:
        prompt: "Press Enter to continue"

    - name: Move VMs to new vSwitch
      ansible.builtin.import_role:
        name: dsu.ccdc.esxi
        tasks_from: update_nic

    - name: Palo NIC
      block:
        - name: Move Palo Alto NICs to new vSwitch
          community.vmware.vmware_guest:
            hostname: "{{ inventory_hostname }}"
            username: "{{ esxi_user }}"
            password: "{{ esxi_password }}"
            validate_certs: false
            name: "Palo"
            # name: test
            networks:
              - name: "{{ default_net | default('VM Network') }}"
              - name: "{{ default_net | default('VM Network') }}"
              - name: "lan"
              - name: "lan3"
              - name: "lan4"
              - name: "lan5"
              - name: "lan6"
              - name: "lan7"
              - name: "lan8"
              - name: "mgt"
          register: new_nic
          delegate_to: localhost
