---
- name: Prep for palo
  hosts: esxi
  # ignore_errors: true
  gather_facts: false
  roles:
    - dsu.ccdc.esxi
  vars:
    esxi_user: root
    # strategy: free

  tasks:
    - name: Import vars
      ansible.builtin.include_vars:
        dir: /home/ansible/vars/
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ new_net }}"
      loop: "{{ esxi_vswitches }}"
      loop_control:
        loop_var: new_net
    - name: Create vSwitch
      when: esxi_vswitches is defined
      ansible.builtin.include_role:
        name: dsu.ccdc.esxi
        tasks_from: vswitch
      loop: "{{ esxi_vswitches }}"
      loop_control:
        loop_var: new_net

    - name: Palo NIC
      community.vmware.vmware_guest:
        hostname: "{{ inventory_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        name: "Palo"
        # name: test
        networks:
          - name: "{{ default_net | default('VM Network') }}"
          - name: "{{ default_net | default('VM Network') }}"
          - name: "lan3"
          - name: "lan4"
          - name: "lan4"
          - name: "lan5"
          - name: "lan6"
          - name: "lan7"
          - name: "lan8"
          - name: "mgt"
      register: new_nic
      delegate_to: localhost
