- name: cert | Generate CA
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd: request certificate generate ca yes ip {{ inventory_hostname }} certificate-name palo-ca name palo algorithm RSA rsa-nbits 4096

- name: cert | Generate Decryption certificate
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd: |
      request certificate generate signed-by palo-ca ca yes hostname palo.ccdc ip {{ inventory_hostname }}
      certificate-name palo-decrypt algorithm RSA rsa-nbits 4096 name palo.ccdc
