# - name: decryption | Generate CA
#   paloaltonetworks.panos.panos_op:
#     provider: "{{ provider }}"
#     cmd_is_xml: true
#     cmd: |
#       <request><certificate><generate>
#         <certificate-name>palo-ca</certificate-name>
#         <name>palo.ccdc</name>
#         <ca>yes</ca>
#         <algorithm>
#         <RSA>
#         <rsa-nbits>2048</rsa-nbits>
#         </RSA>
#         </algorithm>
#       </generate></certificate></request>

# - name: decryption | Generate Decryption certificate
#   paloaltonetworks.panos.panos_op:
#     provider: "{{ provider }}"
#     cmd_is_xml: true
#     cmd: |
#       <request><certificate><generate>
#         <certificate-name>palo-decrypt</certificate-name>
#         <name>palo.ccdc</name>
#         <ca>yes</ca>
#         <signed-by>palo-ca</signed-by>
#         <algorithm>
#         <RSA>
#         <rsa-nbits>2048</rsa-nbits>
#         </RSA>
#         </algorithm>
#       </generate></certificate></request>

- name: decryption | Create Decryption Rule
  paloaltonetworks.panos.panos_decryption_rule:
    provider: "{{ provider }}"
    name: "Decryption Rule"
    action: "decrypt"
    decryption_type: "ssl-forward-proxy"
    decryption_profile: "default"
    source_addresses: "any"
    source_zones: any
    destination_addresses: "any"
    destination_zones: wan
    state: present
    log_successful_tls_handshakes: true
    log_failed_tls_handshakes: true
    log_setting: "Loggie McLog Face"
