- name: decryption | Generate CA
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd_is_xml: true
    cmd: |
      <request><certificate>
      <certificate-name>palo-ca</certificate-name>
      <common-name>palo</common-name>
      <ca>yes</ca>
      <algorithm>RSA</algorithm>
      <rsa-nbits>4096</rsa-nbits>
      </certificate></request>


- name: decryption | Generate Decryption certificate
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd_is_xml: true
    cmd: |
      <request><certificate><generate>
      <certificate-name>palo-decrypt</certificate-name>
      <common-name>palo.ccdc</common-name>
      <hostname>palo.ccdc</hostname>
      <ip>10.20.246.253</ip>
      <signed-by>palo-ca</signed-by>
      <ca>yes</ca>
      <algorithm>RSA</algorithm>
      <rsa-nbits>4096</rsa-nbits>
      </generate></certificate></request>


- name: decryption | Create Decryption Rule
  paloaltonetworks.panos.panos_decryption_rule:
    provider: "{{ provider }}"
    name: "Decryption Rule"
    action: "decrypt"
    decryption_type: "ssl-forward-proxy"
    source_zone: any
    destination_zone: wan
    source_address: "any"
    destination_address: "any"
    state: present
    log_successful_tls_handshakes: true
    log_failed_tls_handshakes: true
