- name: get_zones | Get zones
  paloaltonetworks.panos.panos_zone:
    provider: "{{ provider }}"
    state: gathered
    gathered_filter: "*"
  register: get_zones
  # paloaltonetworks.panos.panos_op:
  # provider: "{{ provider }}"
  # cmd: show interface all

- name: get_zones | Export interface info to file
  delegate_to: localhost
  ansible.builtin.template:
    src: zones.j2
    dest: /home/ansible/test/{{ inventory_hostname }}.yml
    owner: ansible
    group: ansible
    mode: "0644"
