---
# vars file for palo
palo_update_os: false
palo_update_other: false
palo_config_zones: false
palo_config_initial_interface: false
palo_config_initial_groups: false
palo_config_logging: false
palo_config_initial_rules: true
palo_panos_version: 11.1.2
