---
# vars file for ccdc
team_num: 70
palo_ip: 10.{{ team_num }}.{{ team_num }}.250

# Whiteteam IPs
mask_white: 10.120.0.0/24
ntp_white: 10.120.0.10
dns_white: 10.120.0.53
phone_white: 10.120.0.100
ccs_white: 10.120.0.111
proxy_white: 10.120.0.200

# Critical IPs
fw_net: 10.{{ team_num }}.{{ team_num }}.
local_mask: "{{  fw_net }}0/24"
local_dns: "{{ fw_net }}10"
windc: "{{ fw_net }}10"
wazuh: "{{ fw_net }}246"
wazuh_port: "1516"

# Remote IPS
remote_ip: 172.16.{{ team_num }}.
remote_mask: 172.16.{{ team_num }}.0/24
