---
- name: palo | PAN-palo
  ansible.builtin.debug:
    msg: "{{ panos_version }}"

- name: palo | Download PAN-OS update
  paloaltonetworks.panos.panos_software:
    provider: "{{ provider }}"
    version: "{{ panos_version }}"
    install: true
    restart: true
  register: install_result

- name: palo | Notify Reboot Handler
  ansible.builtin.command: echo "Wait for Device Reboot"
  notify: reboot
  changed_when: false

- name: palo | Pause for Restart Checks
  ansible.builtin.pause:
    seconds: 10

- name: palo | Wait for Online Handler
  ansible.builtin.meta: flush_handlers
