---
- name: vswitch | Add a VMware vswitch {{ new_net }}
  delegate_to: localhost
  community.vmware.vmware_vswitch:
    esxi_hostname: "{{ inventory_hostname }}"
    hostname: "{{ inventory_hostname }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_password }}"
    validate_certs: false
    switch: "{{ new_net | default('lan') }}"
    mtu: 1500
    security:
      promiscuous_mode: true
      mac_changes: true
      forged_transmits: true

- name: vswitch | Add Portgroup with all settings defined {{ new_net }}
  delegate_to: localhost
  community.vmware.vmware_portgroup:
    esxi_hostname: "{{ inventory_hostname }}"
    hostname: "{{ inventory_hostname }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_password }}"
    validate_certs: false
    switch: "{{ new_net | default('lan') }}"
    portgroup: "{{ new_net | default('lan') }}"
    security:
      promiscuous_mode: true
      mac_changes: true
      forged_transmits: true
