- name: nic | Get all vm info
  delegate_to: localhost
  community.vmware.vmware_vm_info:
    hostname: "{{ inventory_hostname }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_password }}"
    validate_certs: false
  register: vm_info

- name: nic | Print VM Info
  ansible.builtin.debug:
    var: vm_info

- name: nic | Change NIC for VMs
  delegate_to: localhost
  community.vmware.vmware_guest:
    hostname: "{{ inventory_hostname }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_password }}"
    validate_certs: false
    name: '{{ item.guest_name }}'
    # name: test
    networks:
      - name: protected
  register: new_nic
  loop: "{{ vm_info.virtual_machines | list }}"
