---
- name: Block WAN to esxi
  when:
    - item.value.ip != 0 
    - item.value.fw == 0
    - item.value.service == "esx"
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-{{item.key }}
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: ["{{ local_ip }}{{item.value.ip }}"]
    application: [any]
    action: deny
    location: before
    existing_rule: inbound-safety
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical]
  loop: "{{ services|dict2items }}"

- name: Add SSH rules
  when:
    - item.value.ip != 0 
    - item.value.fw == 0
    - item.value.service == "ssh"
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-{{item.key }}
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: ["{{ local_ip }}{{item.value.ip }}"]
    application: [ssh]
    action: allow
    location: before
    existing_rule: inbound-safety
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Service]
  loop: "{{ services|dict2items }}"

- name: Add SMTP rules
  when:
    - item.value.ip != 0 
    - item.value.fw == 0
    - item.value.service == "smtp"
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-{{  item.key }}
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: ["{{ local_ip }}{{item.value.ip }}"]
    application: [smtp]
    action: allow
    location: before
    existing_rule: inbound-safety
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Service]
  loop: "{{ services|dict2items }}"

- name: Add POP3 rules
  when:
    - item.value.ip != 0 
    - item.value.fw == 0
    - item.value.service == "pop3"
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-{{item.key }}
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: ["{{ local_ip }}{{item.value.ip }}"]
    application: [pop3]
    action: allow
    location: before
    existing_rule: inbound-safety
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Service]
  loop: "{{ services|dict2items }}"

- name: Add HTTP rules
  when:
    - item.value.ip != 0 
    - item.value.fw == 0
    - item.value.service == "http"
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-{{item.key }}
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: ["{{ local_ip }}{{item.value.ip }}"]
    application: [web-browsing]
    action: allow
    location: before
    existing_rule: inbound-safety
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Service]
  loop: "{{ services|dict2items }}"
