---
- name: Phone-in # Don't ask any questions it just needs to be
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: phone-in
    source_zone: [wan]
    source_ip: ["{{  phone_white }}"]
    destination_zone: [lan]
    destination_ip: [any]
    application: [any]
    service: [any]
    action: allow
    location: top # Keep it this way or your life will be ruined
    log_start: true
    log_end: true
    tag_name: [CCDC]


- name: Phone-out
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: phone-out
    source_zone: [lan]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: ["{{  phone_white }}"]
    action: allow
    location: after
    existing_rule: phone-in
    log_start: true
    log_end: true
    tag_name: [CCDC]

- name: CCS-out
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: ccs-out
    source_zone: [any]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: "{{ ccs_white }}"
    application: [any]
    action: allow
    existing_rule: phone-out
    location: after
    log_start: true
    log_end: true
    tag_name: [CCDC]


- name: Proxy-out
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: proxy-out
    source_zone: [any]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: ["{{  proxy_white }}"]
    application: [web-browsing, ssl]
    action: allow
    location: after
    existing_rule: ccs-out
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [CCDC]


- name: White-out
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: white-out
    source_zone: [any]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: ["{{  mask_white }}"]
    application: [any]
    action: allow
    location: after
    existing_rule: proxy-out
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [CCDC]

- name: Inbound-icmp
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-icmp
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: [any]
    application: [ping]
    action: allow
    location: after
    existing_rule: white-out
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [CCDC]


- name: Inbound-rdp
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-rdp
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: [windows]
    application: [ms-rdp]
    action: allow
    location: after
    existing_rule: inbound-icmp
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [CCDC]

- name: Temp block wan
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: temp-wan
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: [9.9.9.9]
    application: [any]
    action: deny
    group_profile: security
    location: after
    existing_rule: inbound-rdp
    log_start: true
    log_end: true
