---
# HTTP
- name: Add HTTP rules
  when: services.ip != 0 && services.fw == palo1 && services.service == http
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-{{ services.service }}
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: ["{{ local_ip }}{{ services.ip }}"]
    application: [web-browsing]
    action: allow
    location: before
    existing_rule: inbound-safety
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Service]
  loop: "{{ services|dict2items }}"

# SSH
- name: Inbound-ssh1
  when: ssh1.ip != 0 && ssh1.fw == palo1 && services.service == ssh
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-ssh1
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: ["{{ local_ip }}{{ ssh1 }}"]
    application: [ssh]
    action: allow
    location: before
    existing_rule: inbound-safety
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Service]

# SMTP
- name: Inbound-smtp1
  when: smtp1.ip != 0 && smtp1.fw == palo1 && services.service == smtp
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-smtp1
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: ["{{ local_ip }}{{ smtp1 }}"]
    application: [smtp]
    action: allow
    location: before
    existing_rule: inbound-safety
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Service]

# POP3
- name: Inbound-pop1
  when: pop1.ip != 0 && pop1.fw == palo1 && services.service == pop
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-pop1
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: ["{{ local_ip }}{{ pop1 }}"]
    application: [pop3]
    action: allow
    location: before
    existing_rule: inbound-safety
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Service]

# DNS
- name: Inbound-dns1
  when: dns1.ip != 0 && dns1.fw == palo1 && services.service == dns
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-dns1
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: [dns_local]
    application: [dns]
    action: allow
    location: before
    existing_rule: inbound-safety
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Service]
