---
- name: Management to all
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: mgt-to-all
    source_zone: [mgt]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: [any]
    application: [any]
    action: allow
    location: after
    existing_rule: inbound-rdp
    log_start: true
    log_end: true
    tag_name: [local]

- name: LAN to ESXI-1
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: lan-esx1
    source_zone: [lan]
    source_ip: [any]
    destination_zone: [esx1]
    destination_ip: ["{{ local_ip }}{{ esx1 }}"]
    application: [vmware, ssl]
    action: allow
    location: after
    existing_rule: mgt-to-all
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [local]

- name: LAN to ESXI-2
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: lan-esx2
    source_zone: [lan]
    source_ip: [any]
    destination_zone: [esx2]
    destination_ip: ["{{ local_ip }}{{ esx2 }}"]
    application: [vmware, ssl]
    action: allow
    location: after
    existing_rule: lan-esx1
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [local]

- name: Add windows server rules
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: lan-winsrv
    source_zone: [lan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: ["{{ win-dc1 }}"]
    application: [winsrv-apps]
    action: allow
    location: after
    existing_rule: lan-esx2
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [local]
