# web-browsing
- name: Inbound-http1
  when: http1 != 0
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http1"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["{{ local_ip }}{{ http1 }}"]
    application: ["web-browsing"]
    action: "allow"
    location: "before"
    existing_rule: "inbound-safety"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Inbound-http2
  when: http2 != 0
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http2"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["{{ local_ip }}{{ http2 }}"]
    application: ["web-browsing"]
    action: "allow"
    location: "before"
    existing_rule: "inbound-safety"
    group_profile: "security"
    log_start: true
    log_end: true

- name: Inbound-http3
  when: http3 != 0
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http3"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["http03"]
    application: ["web-browsing"]
    action: "allow"
    location: "before"
    existing_rule: "inbound-safety"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Inbound-http4
  when: http4 != 0
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http4"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["{{ local_ip }}{{  http4 }}"]
    application: ["web-browsing"]
    action: "allow"
    location: "before"
    existing_rule: "inbound-safety"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Inbound-http5
  when: http5 != 0
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http5"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["{{ local_ip }}{{ http5 }}"]
    application: ["web-browsing"]
    action: "allow"
    location: "before"
    existing_rule: "inbound-safety"
    group_profile: "security"
    log_start: true
    log_end: true
    

# add base rules for ssh
- name: Inbound-ssh1
  when: ssh1 != 0
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-ssh1"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["{{ local_ip }}{{ ssh1 }}"]
    application: ["ssh"]
    action: "allow"
    location: "before"
    existing_rule: "inbound-safety"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Inbound-ssh2
  when: ssh2 != 0
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-ssh2"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["{{ local_ip }}{{ ssh2 }}"]
    application: ["ssh"]
    action: "allow"
    location: "before"
    existing_rule: "inbound-safety"
    log_start: true
    log_end: true
    group_profile: "security"
    

- name: Inbound-ssh3
  when: ssh3 != 0
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-ssh3"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["{{ local_ip }}{{ ssh3 }}"]
    application: ["ssh"]
    action: "allow"
    location: "before"
    existing_rule: "inbound-safety"
    group_profile: "security"
    log_start: true
    log_end: true
    

# add base rules for mail protocols
- name: Inbound-smtp
  when: smtp1 != 0
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-smtp1"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["{{ local_ip }}{{ smtp1 }}"]
    application: ["smtp"]
    action: "allow"
    location: "before"
    existing_rule: "inbound-safety"
    group_profile: "security"
    log_start: true
    log_end: true

- name: Inbound-smtp2
  when: smtp2 != 0
  paloaltonetworks.panos.panos_security_rule:

    

- name: Inbound-pop
  when: pop1 != 0
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-pop1"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["{{ local_ip }}{{ pop1 }}"]
    application: ["pop3"]
    action: "allow"
    location: "before"
    existing_rule: "inbound-safety"
    group_profile: "security"
    log_start: true
    log_end: true
    


# add rules for dns
- name: Inbound-dns
  when: dns1 != 0
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-dns1"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["dns_local"]
    application: ["dns"]
    action: "allow"
    location: "before"
    existing_rule: "inbound-safety"
    group_profile: "security"
    log_start: true
    log_end: true
