- name: Inbound-block-sql
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-sql"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["any"]
    destination_ip: ["any"]
    application: ["mysql"]
    action: "deny"
    group_profile: "security"
    log_start: true
    log_end: true
    group_profile: "security"

- name: Inbound-block-vmware
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-vmware"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["any"]
    destination_ip: ["any"]
    application: ["vmware", "vmware-update", "vmware-view"]
    action: "deny"
    log_start: true
    log_end: true
    group_profile: "security"    

# web-browsing
- name: Inbound-http1
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http-1"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["web-browsing"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Inbound-http2
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http2"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["web-browsing"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Inbound-http3
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http3"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["web-browsing"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Inbound-http4
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http4"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["web-browsing"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Inbound-http5
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-http5"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["web-browsing"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"
    

# add base rules for ssh
- name: Inbound-ssh1
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-ssh1"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["ssh"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Inbound-ssh2
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-ssh2"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["ssh"]
    action: "allow"
    log_start: true
    log_end: true
    group_profile: "security"
    

- name: Inbound-ssh3
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-ssh3"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["ssh"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    

# add base rules for mail protocols
- name: Inbound-smtp
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-smtp"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["smtp"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Inbound-pop
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-pop"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["pop3"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    


# add rules for dns
- name: Inbound-dns
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-dns"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["dns_local"]
    application: ["dns"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    

# Safety rule
- name: Inbound safety
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-safety"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["safe"]
    action: "deny"
    group_profile: "security"
    log_start: true
    log_end: true
    


# Allow all traffic
- name: Allow all traffic in
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-all"
    source_zone: ["any"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["any"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Allow all traffic out
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-all"
    source_zone: ["lan"]
    source_ip: ["any"]
    destination_zone: ["any"]
    destination_ip: ["any"]
    application: ["any"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    

- name: Add windows server rules
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "lan to windows-server"
    source_zone: ["lan"]
    source_ip: ["windows"]
    destination_zone: ["winsrv"]
    destination_ip: ["winsrv"]
    application: ["winsrv-apps"]
    action: "allow"
    group_profile: "security"
    log_start: true
    log_end: true
    


- name: Add outbound block rule
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "outbound-block-all"
    source_zone: ["any"]
    source_ip: ["lan"]
    destination_zone: ["any"]
    destination_ip: ["any"]
    application: ["any"]
    action: "deny"
    group_profile: "security"
    log_start: true
    log_end: true
    
- name: Add inbound block rule
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-block-all"
    source_zone: ["wan"]
    source_ip: ["any"]
    destination_zone: ["lan"]
    destination_ip: ["any"]
    application: ["any"]
    action: "deny"
    group_profile: "security"
    log_start: true
    log_end: true

# - name: Set initial rules as done
#   set_fact:
#     config_initial_rules: "n"
#     cacheable: true
