---
- name: restore | Firewall restore
  hosts: wrccdc_fw
  # connection: local
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: Save current state of the firewall
      community.general.iptables_state:
        state: restored
        path: /etc/sysconfig/iptables.rules
    - name: restore file
      deligate_to: localhost
      ansible.builtin.fetch:
        src: /etc/sysconfig/iptables.rules
        dest: /home/ansible/data/backup/firewall/
        flat: true
