services:
  esx1: 
    ip: 40
    fw: 0
    service: esx
  esx2: 
    ip: 45
    fw: 0
    service: esx
  esx3: 
    ip: 0
    fw: 0
    service: esx
  esx4: 
    ip: 0
    fw: 0
    service: esx
  esx5: 
    ip: 0
    fw: 0
    service: esx
  esx6: 
    ip: 0
    fw: 0
    service: esx

  # Windows DCs
  dc1: 
    ip: 10
    fw: 0
    service: dc
  dc2: 
    ip: 0
    fw: 0
    service: dc
  dc3: 
    ip: 0
    fw: 0
    service: dc
  dc4: 
    ip: 0
    fw: 0
    service: dc
  dc5: 
    ip: 0
    fw: 0
    service: dc
  dc6: 
    ip: 0
    fw: 0
    service: dc
  dc7: 
    ip: 0
    fw: 0
    service: dc
  dc8: 
    ip: 0
    fw: 0
    service: dc
  dc9: 
    ip: 0
    fw: 0
    service: dc
  dc10: 
    ip: 0
    fw: 0
    service: dc

  # DNS
  dns1: 
    ip: 10
    fw: 0
    service: dns
  dns2: 
    ip: 0
    fw: 0
    service: dns
  dns3: 
    ip: 0
    fw: 0
    service: dns
  dns4: 
    ip: 0
    fw: 0
    service: dns
  dns5: 
    ip: 0
    fw: 0
    service: dns
  dns6: 
    ip: 0
    fw: 0
    service: dns
  dns7: 
    ip: 0
    fw: 0
    service: dns
  dns8: 
    ip: 0
    fw: 0
    service: dns
  dns9: 
    ip: 0
    fw: 0
    service: dns
  dns10: 
    ip: 0
    fw: 0
    service: dns

  # SSH
  ssh1: 
    ip: 13
    fw: 0
    service: ssh
  ssh2: 
    ip: 0
    fw: 0
    service: ssh
  ssh3: 
    ip: 13
    fw: 0
    service: ssh
  ssh4: 
    ip: 0
    fw: 0
    service: ssh
  ssh5: 
    ip: 0
    fw: 0
    service: ssh
  ssh6: 
    ip: 0
    fw: 0
    service: ssh
  ssh7: 
    ip: 0
    fw: 0
    service: ssh
  ssh8: 
    ip: 0
    fw: 0
    service: ssh
  ssh9: 
    ip: 0
    fw: 0
    service: ssh
  ssh10: 
    ip: 0
    fw: 0
    service: ssh

  # POP3
  pop1: 
    ip: 30
    fw: 0
    service: pop
  pop2: 
    ip: 0
    fw: 0
    service: pop
  pop3: 
    ip: 0
    fw: 0
    service: pop
  pop4: 
    ip: 0
    fw: 0
    service: pop
  pop5: 
    ip: 0
    fw: 0
    service: pop

  # SMTP
  smtp1: 
    ip: 30
    fw: 0
    service: smtp
  smtp2: 
    ip: 0
    fw: 0
    service: smtp
  smtp3: 
    ip: 0
    fw: 0
    service: smtp
  smtp4: 
    ip: 0
    fw: 0
    service: smtp
  smtp5: 
    ip: 0
    fw: 0
    service: smtp

  # HTTP
  http1: 
    ip: 60
    fw: 0
    service: http
  http2: 
    ip: 61
    fw: 0
    service: http
  http3: 
    ip: 62
    fw: 0
    service: http
  http4: 
    ip: 63
    fw: 0
    service: http
  http5: 
    ip: 64
    fw: 0
    service: http
  http6: 
    ip: 65
    fw: 0
    service: http
  http7: 
    ip: 66
    fw: 0
    service: http
  http8: 
    ip: 67
    fw: 0
    service: http
  http9: 
    ip: 68
    fw: 0
    service: http
  http10: 
    ip: 69
    fw: 0
    service: http
  http11: 
    ip: 70
    fw: 0
    service: http
  http12: 
    ip: 71
    fw: 0
    service: http
  http13: 
    ip: 72
    fw: 0
    service: http
  http14: 
    ip: 73
    fw: 0
    service: http
  http15: 
    ip: 74
    fw: 0
    service: http
  http16: 
    ip: 75
    fw: 0
    service: http
  http17: 
    ip: 76
    fw: 0
    service: http
  http18: 
    ip: 77
    fw: 0
    service: http
  http19: 
    ip: 78
    fw: 0
    service: http
  http20: 
    ip: 79
    fw: 0
    service: http
  http21: 
    ip: 80
    fw: 0
    service: http
  http22: 
    ip: 81
    fw: 0
    service: http
  http23: 
    ip: 82
    fw: 0
    service: http
  http24: 
    ip: 83
    fw: 0
    service: http
  http25: 
    ip: 84
    fw: 0
    service: http
  http26: 
    ip: 85
    fw: 0
    service: http
  http27: 
    ip: 86
    fw: 0
    service: http
  http28: 
    ip: 87
    fw: 0
    service: http
  http29: 
    ip: 88
    fw: 0
    service: http
  http30: 
    ip: 89
    fw: 0
    service: http
  http31: 
    ip: 90
    fw: 0
    service: http
  http32: 
    ip: 91
    fw: 0
    service: http
  http33: 
    ip: 92
    fw: 0
    service: http
  http34: 
    ip: 93
    fw: 0
    service: http
  http35: 
    ip: 94
    fw: 0
    service: http
  http36: 
    ip: 95
    fw: 0
    service: http
  http37: 
    ip: 96
    fw: 0
    service: http
  http38: 
    ip: 97
    fw: 0
    service: http
  http39: 
    ip: 98
    fw: 0
    service: http
  http40: 
    ip: 99
    fw: 0
    service: http