---
- name: os_update | PAN-OS_update
  ansible.builtin.debug:
    msg: "{{ panos_version }}"

- name: os_update | Download PAN-OS update
  paloaltonetworks.panos.panos_software:
    provider: "{{ provider }}"
    version: "{{ panos_version }}"
    install: true
    restart: true
  register: install_result

- name: os_update | Notify Reboot Handler
  ansible.builtin.command: echo "Wait for Device Reboot"
  notify: reboot
  changed_when: false

- name: os_update | Pause for Restart Checks
  ansible.builtin.pause:
    seconds: 10

- name: os_update | Wait for Online Handler
  ansible.builtin.meta: flush_handlers
