---
- name: snapshot | List all existing virtual machines on node
  community.general.proxmox_vm_info:
    api_host: "{{ ip_address }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ api_password }}"
    node: node01

- name: snapshot | Create new container snapshot
  community.general.proxmox_snap:
    api_host: "{{ ip_address }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ api_password }}"
    vmid: 
    state: present
    snapname: pre-updates


