---
- name: address | Add LAN Address
  paloaltonetworks.panos.panos_address_object:
    provider: "{{ provider }}"
    name: lan
    value: "{{ local_mask }}"

- name: address | Add windows server address group
  when: ("dc" in item.value.svc)
  paloaltonetworks.panos.panos_address_group:
    provider: "{{ provider }}"
    name: windc
    dynamic_value: dc
  loop: "{{ services.palo | dict2items }}"

- name: address | Add esx address group
  when: ( "esx" in item.value.svc)
  paloaltonetworks.panos.panos_address_group:
    provider: "{{ provider }}"
    name: esxi
    dynamic_value: esx
  loop: "{{ services.palo | dict2items }}"

- name: address | Add windows address group
  when: ("windows" in item.value.svc) or ("dc" in item.value.svc)
  paloaltonetworks.panos.panos_address_group:
    provider: "{{ provider }}"
    name: windows
    dynamic_value: windows
  loop: "{{ services.palo | dict2items }}"
