---
- name: all_updates | Update anti-virus
  ansible.builtin.import_tasks: av_update.yml
  when: palo_update_other

- name: all_updates | Update content
  ansible.builtin.import_tasks: content_update.yml
  when: palo_update_other

- name: all_updates | Update wildfire
  ansible.builtin.import_tasks: wildfire_update.yml
  when: palo_update_other

- name: all_updates | Set other updates as complete
  ansible.builtin.set_fact:
    palo_update_other: false
