---
- name: certs | Configure Palo Certs
  paloaltonetworks.panos.panos_cert_gen_ssh:
    ip_address: "{{ palo_ip }}"
    username: admin
    cert_cn: Palo
    cert_friendly_name: palo_ssh
    signed_by: root-ca
