---
- name: os_update | PAN-OS_update
  ansible.builtin.debug:
    msg: "{{ palo_panos_version }}"

- name: os_update | Download PAN-OS update
  paloaltonetworks.panos.panos_software:
    provider: "{{ provider }}"
    version: "{{ palo_panos_version }}"
    install: true
    restart: true
  register: install_result

- name: os_update | Notify Reboot Handler
  ansible.builtin.command: echo "Wait for Device Reboot"
  notify: reboot
  changed_when: false

- name: os_update | Pause for Restart Checks
  ansible.builtin.pause:
    seconds: 30

- name: os_update | Check to see if device is ready
  paloaltonetworks.panos.panos_op:
    provider: '{{ provider }}'
    cmd: 'show chassis-ready'
  changed_when: false
  register: result
  until: result is not failed and (result.stdout | from_json).response.result == "yes"
  retries: 90
  delay: 5

- name: os_update | Wait for Online Handler
  ansible.builtin.meta: flush_handlers

- name: os_update | Set os_update as done
  ansible.builtin.set_fact:
    palo_update_os: false
    cacheable: true
  when: palo_update_os
