---
- name: palo_local | LAN to DC
  when: ("dc" in item.value.svc)
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: lan-windc{{ item.key }}
    source_zone: [lan]
    source_ip: [any]
    destination_zone: ["{{ item.value.zone | default('lan') }}"]
    destination_ip: ["{{ item.value.ip |  default(fw_net ~ item.key) }}"]
    application: [windc]
    action: allow
    location: before
    existing_rule: tmp-block
    group_profile: security
    log_start: true
    log_end: true
    log_setting: "Loggie McLog Face"
    tag_name: [local]
  loop: "{{ services.palo | dict2items }}"

- name: palo_local | LAN to ESXI
  when: ( "esx" in item.value.svc)
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: lan-esx{{ item.key }}
    source_zone: [lan]
    source_ip: [any]
    destination_zone: ["{{ item.value.zone | default('lan') }}"]
    destination_ip: ["{{ item.value.ip |  default(fw_net ~ item.key) }}"]
    application: [vmware, ssl]
    action: allow
    location: before
    existing_rule: tmp-block
    group_profile: security
    log_start: true
    log_end: true
    log_setting: "Loggie McLog Face"
    tag_name: [local]
  loop: "{{ services.palo | dict2items }}"

- name: palo_local | Block WAN to DC
  when: ("dc" in item.value.svc)
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-dc{{ item.key }}
    source_zone: [wan]
    source_ip: [any]
    destination_zone: ["{{ item.value.zone | default('lan') }}"]
    destination_ip: ["{{ item.value.ip |  default(fw_net ~ item.key) }}"]
    application: [windc]
    action: deny
    group_profile: security
    location: before
    existing_rule: tmp-block
    log_start: true
    log_end: true
    log_setting: "Loggie McLog Face"
    tag_name: [Critical]
  loop: "{{ services.palo | dict2items }}"

- name: palo_local | Block WAN to ESXI
  when: ("esx" in item.value.svc)
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-esx{{ item.key }}
    source_zone: [wan]
    source_ip: [any]
    destination_zone: ["{{ ip.value.zone | default('lan') }}"]
    destination_ip: ["{{ item.value.ip |  default(fw_net ~ item.key) }}"]
    application: [any]
    action: deny
    location: before
    existing_rule: tmp-block
    group_profile: security
    log_start: true
    log_end: true
    log_setting: "Loggie McLog Face"
    tag_name: [Critical]
  loop: "{{ services.palo | dict2items }}"
