---
- name: palo_critical | Inbound-block-sql
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-sql
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: [any]
    application: [mysql, postgres, mongodb]
    action: deny
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical]

- name: palo_critical | Allow DC access to DNS
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-dns
    source_zone: [lan]
    source_ip: ["{{ local_dns }}"]
    destination_zone: [wan]
    destination_ip: [1.1.1.1]
    application: [dns]
    action: allow
    group_profile: security
    location: after
    existing_rule: inbound-sql
    log_start: true
    log_end: true
    tag_name: [Critical]

# Allow all traffic
- name: palo_critical | Allow all traffic in
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-all
    source_zone: [any]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: [any]
    application: [any]
    action: allow
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical, ALLOW ALL]

- name: palo_critical | Allow web outbound
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-web
    source_zone: [lan]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: [any]
    application: [web-browsing, ssl]
    action: allow
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical]

- name: palo_critical | Block DNS outbound
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-DNS
    source_zone: [any]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: [any]
    application: [dns]
    action: deny
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical]

- name: palo_critical | Allow all traffic out
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-ALLOW
    source_zone: [lan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: [any]
    application: [any]
    action: allow
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical, ALLOW ALL]

- name: palo_critical | Add outbound block rule
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-all
    source_zone: [any]
    source_ip: [lan]
    destination_zone: [any]
    destination_ip: [any]
    application: [any]
    action: deny
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical, BLOCK ALL]

- name: palo_critical | Add inbound block rule
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-ALLOW
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: [any]
    application: [any]
    action: deny
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical, BLOCK ALL]


- name: palo_critical | Tmp block wan
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: tmp-block
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: [9.9.9.9]
    application: [any]
    action: deny
    group_profile: security
    location: after
    existing_rule: outbound-dns
    log_start: true
    log_end: true

- name: palo_critical | Management to all
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: mgt-all
    source_zone: [mgt]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: [any]
    application: [any]
    action: allow
    location: after
    existing_rule: inbound-rdp
    log_start: true
    log_end: true
    tag_name: [local]
