---
- name: palo_service | Create service rules
  when: item.key not in fw_block
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "inbound-{{ item.key }}{{ host.key }}"
    source_zone: [wan]
    source_ip: [any]
    destination_zone: ["{{ host.value.zone | default('lan') }}"]
    destination_ip: ["{{ item.value.ip |  default(fw_net ~ host.key) }}"]
    application: "{{ palo_svc[item.key] }}"
    action: allow
    location: before
    existing_rule: inbound-all
    group_profile: security
    log_start: true
    log_end: true
    log_setting: "Loggie McLog Face"
    tag_name: [Service]
  loop: "{{ host.value.svc | dict2items | list }}"
