---
- name: palo-rules | Add CCDC firewall Rules
  ansible.builtin.import_tasks: palo-ccdc.yml
  when: config_initial_rules == "y"

- name: palo-rules |  Add local firewall Rules
  ansible.builtin.import_tasks: palo-local.yml
  when: config_initial_rules == "y"

- name: palo-rules | Add block firewall rules
  ansible.builtin.import_tasks: palo-critical.yml
  when: config_initial_rules == "y"

- name: palo-rules |  Add comp firewall rules
  ansible.builtin.import_tasks: palo-service.yml
  when: config_initial_rules == "y"

- name: palo-rules | Commit rule changes
  ansible.builtin.import_tasks: palo/tasks/commit.yml
  when: config_initial_rules == "y"
