---
- name: palo_local | Management to all
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: mgt-to-all
    source_zone: [mgt]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: [any]
    application: [any]
    action: allow
    location: after
    existing_rule: inbound-rdp
    log_start: true
    log_end: true
    tag_name: [local]

- name: palo_local | LAN to ESXI
  when: (item.value.ip != 0) and (item.value.service == 'esx')
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: lan-{{  item.key }}
    source_zone: [lan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: ["{{ fw_net }}{{ item.value.ip }}"]
    application: [vmware, ssl]
    action: allow
    location: after
    existing_rule: mgt-all
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [local]
  loop: "{{ services | dict2items }}"

- name: palo_local | Add windows server rules
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: lan-windc
    source_zone: [lan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: ["windc"]
    application: [winsrv]
    action: allow
    location: after
    existing_rule: mgt-to-all
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [local]
