---
- name: palo_ccdc | Show IPs
  ansible.builtin.debug:
    msg:
      Phone White: "{{ phone_white }}"
      CCS White: "{{ ccs_white }}"
      Proxy White: "{{ proxy_white }}"
      Mask White: "{{ mask_white }}"

- name: palo_ccdc | Inbound phone # Don't ask any questions it just needs to be
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-phone
    source_zone: [wan]
    source_ip: ["{{ phone_white }}"]
    destination_zone: [lan]
    destination_ip: [any]
    application: [any]
    service: [any]
    action: allow
    location: top # Keep it this way or your life will be ruined
    log_start: true
    log_end: true
    tag_name: [CCDC]

- name: palo_ccdc | Outbound phone
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-phone
    source_zone: [lan]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: ["{{  phone_white }}"]
    action: allow
    location: after
    existing_rule: inbound-phone
    log_start: true
    log_end: true
    tag_name: [CCDC]
- name: palo_ccdc | Outbound CCS
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-ccs
    source_zone: [any]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: "{{ ccs_white }}"
    application: [any]
    action: allow
    existing_rule: outbound-phone
    location: after
    log_start: true
    log_end: true
    tag_name: [CCDC]
- name: palo_ccdc | Outbound proxy
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-proxy
    source_zone: [any]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: ["{{  proxy_white }}"]
    application: [web-browsing, ssl]
    action: allow
    location: after
    existing_rule: outbound-ccs
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [CCDC]
- name: palo_ccdc | Outbound white team
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-whiteteam
    source_zone: [any]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: ["{{  mask_white }}"]
    application: [any]
    action: allow
    location: after
    existing_rule: outbound-proxy
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [CCDC]
- name: palo_ccdc | Inbound icmp
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-icmp
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: [any]
    application: [ping]
    action: allow
    location: after
    existing_rule: outbound-whiteteam
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [CCDC]
- name: palo_ccdc | Inbound dp
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-rdp
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: [windows]
    application: [ms-rdp]
    action: allow
    location: after
    existing_rule: inbound-icmp
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [CCDC]
- name: palo_ccdc | Temp block wan
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: temp-blockWan
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: [9.9.9.9]
    application: [any]
    action: deny
    group_profile: security
    location: after
    existing_rule: inbound-rdp
    log_start: true
    log_end: true
