---
- name: palo_service | Add service rules for {{ service.key }}
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-{{ service.key }}{{ item.key }}
    source_zone: ["{{ alias.wan | default('wan') }}"]
    source_ip: [any]
    destination_zone: ["{{ item.value if item.value is not none else alias.lan | default('lan') }}"]
    destination_ip: ["{{ item.value.ip |  default(fw_net ~ item.key) }}"]
    application: "{{ palo.svc[service.key] }}"
    action: allow
    location: before
    existing_rule: inbound-all
    group_profile: security
    log_start: true
    log_end: true
    log_setting: Loggie McLog Face
    tag_name: [Service]
  loop: "{{ service.value | dict2items }}"
