---
- name: wildfire_update | Check for wildfire updated
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd: request wildfire upgrade check
  register: check

- name: wildfire_update | Download latest content
  # Download the latest version
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd: |
      <request><wildfire><upgrade><download>
      <latest></latest>
      </download></upgrade></wildfire></request>
    cmd_is_xml: true
  register: download

- name: wildfire_update | Check content download result
  # wait for this job to finish
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd: show jobs id {{ (download.stdout | from_json).response.result.job }}
  register: download_job
  until: download_job is not failed and (download_job.stdout | from_json).response.result.job.status == 'FIN'
  retries: 75
  delay: 5

- name: wildfire_update | Install latest content
  # Content is downloaded and ready, now install it
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd: |
      <request><wildfire><upgrade><install>
      <version>latest</version>
      </install></upgrade></wildfire></request>
    cmd_is_xml: true
  register: install
