---
palo:
  hosts:
    palo1:
      ip_address: 10.20.20.60
      api_key: ""
    palo2:
      ip_address: 10.20.20.61
      api_key: ""
  vars:
    ansible_user: admin

cisco:
  hosts: 
    cisco1:
    cisco2:
  vars:
    ansible_user: admin
    ansible_password: ""
    ansible_httpapi_validate_certs: False
    ansible_network_os: cisco.fmcansible.fmc


esxi: 
  hosts: 
    esxi1:
      ansible_host: 10.20.20.10
      esxi_password: ""
    esxi2:
      ansible_host: 10.20.20.15
      esxi_password: ""
  vars:
    esxi_username: root 
    validate_certs: False

