- name: Palo test
  hosts: palo
  connection: local
  ignore_errors: true
  roles:
    - dsu.ccdc.palo
  vars:
    provider:
      ip_address: "{{ inventory_hostname }}"
      api_key: "{{ api_key }}"


  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: dsu.ccdc.palo

    - name: Include IP vars
      ansible.builtin.include_vars:
        dir: vars/

    - name: Print configs
      ansible.builtin.debug:
        msg:
          Update OS: "{{ palo_update_os }}"
          Update Other: "{{ palo_update_other }}"
          Initial Interface: "{{ palo_config_initial_interface }}"
          Initial Groups: "{{ palo_config_initial_groups }}"
          Logging: "{{ palo_config_logging }}"
          Initial Rules: "{{ palo_config_initial_rules }}"
          PANOS Version: "{{ palo_panos_version }}"
          # IP Range: "{{ ip_range }}"
          # Network: "{{ ip_range_mask }}"
          Wazuh: "{{ wazuh }}"
          Wazuh Port: "{{ wazuh_port }}"
