---
name: Antsibull

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  release:
    types: [ merge ]
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: "Run antsichaut"
        uses: ansible-community/antsichaut@main
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          since_version: "${{ steps.previoustag.outputs.tag }}"
