name: Create new branch for issues
on:
  issues:
    types:
      - opened
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: robvanderleek/create-issue-branch@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
